export enum ACCOUNT_DATA_ACTIONS {
  ACCOUNT_DATA_REQUEST = 'ACCOUNT_DATA_REQUEST',
  ACCOUNT_DATA_SUCCESS = 'ACCOUNT_DATA_SUCCESS',
  ACCOUNT_DATA_ERROR = 'ACCOUNT_DATA_ERROR',
  ACCOUNT_DATA_RESET = 'ACCOUNT_DATA_RESET',
  GET_MORE_ACCOUNT_DATA_REQUEST = 'GET_MORE_ACCOUNT_DATA_REQUEST',
  GET_MORE_ACCOUNT_DATA_SUCCESS = 'GET_MORE_ACCOUNT_DATA_SUCCESS',
  GET_MORE_ACCOUNT_DATA_ERROR = 'GET_MORE_ACCOUNT_DATA_ERROR',
}