export enum CLIENT_USERS_ACTIONS {
  CLIENT_USERS_REQUEST = 'CLIENT_USERS_REQUEST',
  CLIENT_USERS_SUCCESS = 'CLIENT_USERS_SUCCESS',
  CLIENT_USERS_ERROR = 'CLIENT_USERS_ERROR',
  CLIENT_USERS_RESET = 'CLIENT_USERS_RESET',
  GET_MORE_CLIENT_USERS_REQUEST = 'GET_MORE_CLIENT_USERS_REQUEST',
  GET_MORE_CLIENT_USERS_SUCCESS = 'GET_MORE_CLIENT_USERS_SUCCESS',
  GET_MORE_CLIENT_USERS_ERROR = 'GET_MORE_CLIENT_USERS_ERROR',
}
