export enum G2K_FINANCIALS_ACTIONS {
  G2K_FINANCIALS_REQUEST = 'G2K_FINANCIALS_REQUEST',
  G2K_FINANCIALS_SUCCESS = 'G2K_FINANCIALS_SUCCESS',
  G2K_FINANCIALS_ERROR = 'G2K_FINANCIALS_ERROR',
  G2K_FINANCIALS_RESET = 'G2K_FINANCIALS_RESET',
}