export enum ACCOUNT_TEAM_ACTIONS {
  ACCOUNT_TEAM_REQUEST = 'ACCOUNT_TEAM_REQUEST',
  ACCOUNT_TEAM_SUCCESS = 'ACCOUNT_TEAM_SUCCESS',
  ACCOUNT_TEAM_ERROR = 'ACCOUNT_TEAM_ERROR',
  ACCOUNT_TEAM_RESET = 'ACCOUNT_TEAM_RESET',
  GET_MORE_ACCOUNT_TEAM_REQUEST = 'GET_MORE_ACCOUNT_TEAM_REQUEST',
  GET_MORE_ACCOUNT_TEAM_SUCCESS = 'GET_MORE_ACCOUNT_TEAM_SUCCESS',
  GET_MORE_ACCOUNT_TEAM_ERROR = 'GET_MORE_ACCOUNT_TEAM_ERROR',
}