export enum USER_PREFERENCE_ACTIONS {
  USER_PREFERENCE_REQUEST = 'USER_PREFERENCE_REQUEST',
  USER_PREFERENCE_SUCCESS = 'USER_PREFERENCE_SUCCESS',
  USER_PREFERENCE_ERROR = 'USER_PREFERENCE_ERROR',
  USER_PREFERENCE_RESET = 'USER_PREFERENCE_RESET',
}

export enum UPDATE_USER_PREFERENCES_ACTIONS {
  UPDATE_USER_PREFERENCES_REQUEST = 'UPDATE_USER_PREFERENCES_REQUEST',
  UPDATE_USER_PREFERENCES_SUCCESS = 'UPDATE_USER_PREFERENCES_SUCCESS',
  UPDATE_USER_PREFERENCES_ERROR = 'UPDATE_USER_PREFERENCES_ERROR',
  UPDATE_USER_PREFERENCES_RESET = 'UPDATE_USER_PREFERENCES_RESET',
}