export enum CLIENT_DATA_ACTIONS {
  CLIENT_DATA_REQUEST = 'CLIENT_DATA_REQUEST',
  CLIENT_DATA_SUCCESS = 'CLIENT_DATA_SUCCESS',
  CLIENT_DATA_ERROR = 'CLIENT_DATA_ERROR',
  CLIENT_DATA_RESET = 'CLIENT_DATA_RESET',
  // GET_MORE_CLIENT_DATA_REQUEST = 'GET_MORE_CLIENT_DATA_REQUEST',
  // GET_MORE_CLIENT_DATA_SUCCESS = 'GET_MORE_CLIENT_DATA_SUCCESS',
  // GET_MORE_CLIENT_DATA_ERROR = 'GET_MORE_CLIENT_DATA_ERROR',
  SET_IS_CLIENT_SELECTED = 'SET_IS_CLIENT_SELECTED',
  RESET_IS_CLIENT_SELECTED = 'RESET_IS_CLIENT_SELECTED'
}
