export enum ACCOUNT_SUMMARY_ACTIONS {
  ACCOUNT_SUMMARY_REQUEST = 'ACCOUNT_SUMMARY_REQUEST',
  ACCOUNT_SUMMARY_SUCCESS = 'ACCOUNT_SUMMARY_SUCCESS',
  ACCOUNT_SUMMARY_ERROR = 'ACCOUNT_SUMMARY_ERROR',
  ACCOUNT_SUMMARY_RESET = 'ACCOUNT_SUMMARY_RESET'
}