export enum UPLOAD_ACTIONS {
    UPLOAD_DATA_INITIATE = 'UPLOAD_DATA_INITIATE',
    UPLOAD_DATA_ERROR = 'UPLOAD_DATA_ERROR',
    UPLOAD_DATA_SUCCESS ='UPLOAD_DATA_SUCCESS',
    RESET_UPLOAD_DATA ='RESET_UPLOAD_DATA'
  };