export enum REVENUE_PLAN_ACTIONS {
  REVENUE_PLAN_REQUEST = 'REVENUE_PLAN_REQUEST',
  REVENUE_PLAN_SUCCESS = 'REVENUE_PLAN_SUCCESS',
  REVENUE_PLAN_ERROR = 'REVENUE_PLAN_ERROR',
  REVENUE_PLAN_RESET = 'REVENUE_PLAN_RESET'
}

export enum PGI_GRAPH_ACTIONS {
  PGI_GRAPH_DATA_REQUEST = 'PGI_GRAPH_DATA_REQUEST',
  PGI_GRAPH_DATA_SUCCESS = 'PGI_GRAPH_DATA_SUCCESS',
  PGI_GRAPH_DATA_ERROR = 'PGI_GRAPH_DATA_ERROR',
  PGI_GRAPH_DATA_RESET = 'PGI_GRAPH_DATA_RESET'
}

export enum PROD_CAT_FILTER_ACTIONS {
  PROD_CAT_FILTER_REQUEST = 'PROD_CAT_FILTER_REQUEST',
  PROD_CAT_FILTER_SUCCESS = 'PROD_CAT_FILTER_SUCCESS',
  PROD_CAT_FILTER_ERROR = 'PROD_CAT_FILTER_ERROR',
  PROD_CAT_FILTER_RESET = 'PROD_CAT_FILTER_RESET',
  GET_MORE_PROD_CAT_FILTER_REQUEST = 'GET_MORE_PROD_CAT_FILTER_REQUEST',
  GET_MORE_PROD_CAT_FILTER_SUCCESS = 'GET_MORE_PROD_CAT_FILTER_SUCCESS',
  GET_MORE_PROD_CAT_FILTER_ERROR = 'GET_MORE_PROD_CAT_FILTER_ERROR',
}

export enum BC_ESTIMATES_ACTIONS {
  BC_ESTIMATES_DATA_REQUEST = 'BC_ESTIMATES_DATA_REQUEST',
  BC_ESTIMATES_DATA_SUCCESS = 'BC_ESTIMATES_DATA_SUCCESS',
  BC_ESTIMATES_DATA_ERROR = 'BC_ESTIMATES_DATA_ERROR',
  BC_ESTIMATES_DATA_RESET = 'BC_ESTIMATES_DATA_RESET'
}