export enum USER_PROFILE_ACTIONS {
  GET_USER_PROFILE_REQUEST = 'GET_USER_PROFILE_REQUEST',
  GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS',
  GET_USER_PROFILE_ERROR = 'GET_USER_PROFILE_ERROR',
}

export enum EDIT_USER_PROFILE_ACTIONS {
  EDIT_USER_PROFILE_REQUEST = 'EDIT_USER_PROFILE_REQUEST',
  EDIT_USER_PROFILE_ERROR = 'EDIT_USER_PROFILE_ERROR',
  EDIT_USER_PROFILE_SUCCESS ='EDIT_USER_PROFILE_SUCCESS',
  RESET_EDIT_USER_PROFILE ='RESET_EDIT_USER_PROFILE',
};