export enum PC_TEMPLATES_ACTIONS {
  PC_TEMPLATES_REQUEST = 'PC_TEMPLATES_REQUEST',
  PC_TEMPLATES_SUCCESS = 'PC_TEMPLATES_SUCCESS',
  PC_TEMPLATES_ERROR = 'PC_TEMPLATES_ERROR',
  PC_TEMPLATES_RESET = 'PC_TEMPLATES_RESET',
  PC_DEFAULT_TEMPLATE = 'PC_DEFAULT_TEMPLATE',
}

export enum GET_TEMPLATE_COLUMNS_ACTIONS {
  GET_TEMPLATE_COLUMNS_REQUEST = 'GET_TEMPLATE_COLUMNS_REQUEST',
  GET_TEMPLATE_COLUMNS_SUCCESS = 'GET_TEMPLATE_COLUMNS_SUCCESS',
  GET_TEMPLATE_COLUMNS_FAILURE = 'GET_TEMPLATE_COLUMNS_FAILURE',
  GET_TEMPLATE_COLUMNS_DD_UPDATE = 'GET_TEMPLATE_COLUMNS_DD_UPDATE',
  ADD_TEMPLATE_COLUMN = 'ADD_TEMPLATE_COLUMN',
  DELETE_TEMPLATE_COLUMN = 'DELETE_TEMPLATE_COLUMN',
  RESET_TEMPLATE_COLUMN = 'RESET_TEMPLATE_COLUMN',
  TEMPLATE_VIEW_COLUMNS = 'TEMPLATE_VIEW_COLUMNS',
  TEMPLATE_EDIT_COLUMNS_REQUEST = 'TEMPLATE_EDIT_COLUMNS_REQUEST',
  TEMPLATE_EDIT_COLUMNS_SUCCESS = 'TEMPLATE_EDIT_COLUMNS_SUCCESS',
  TEMPLATE_EDIT_COLUMNS_FAILURE = 'TEMPLATE_EDIT_COLUMNS_FAILURE',
  EDIT_TEMPLATE_COLUMNS_DD_UPDATE = 'EDIT_TEMPLATE_COLUMNS_DD_UPDATE'
}

export enum TEMPLATE_MANAGER_ACTIONS {
  TEMPLATE_MANAGER_REQUEST = 'TEMPLATE_MANAGER_REQUEST',
  TEMPLATE_MANAGER_SUCCESS = 'TEMPLATE_MANAGER_SUCCESS',
  TEMPLATE_MANAGER_ERROR = 'TEMPLATE_MANAGER_ERROR',
  TEMPLATE_MANAGER_RESET = 'TEMPLATE_MANAGER_RESET',
}

export enum TEMPLATE_DELETE_ACTIONS {
  TEMPLATE_DELETE_REQUEST = 'TEMPLATE_DELETE_REQUEST',
  TEMPLATE_DELETE_SUCCESS = 'TEMPLATE_DELETE_SUCCESS',
  TEMPLATE_DELETE_ERROR = 'TEMPLATE_DELETE_ERROR',
  TEMPLATE_DELETE_RESET = 'TEMPLATE_DELETE_RESET',
}

export enum CREATE_TEMPLATE_ACTIONS {
  CREATE_TEMPLATE_REQUEST = 'CREATE_TEMPLATE_REQUEST',
  CREATE_TEMPLATE_SUCCESS = 'CREATE_TEMPLATE_SUCCESS',
  CREATE_TEMPLATE_ERROR = 'CREATE_TEMPLATE_ERROR',
}