export enum USER_ONBOARDING_STATUS_ACTIONS {
  GET_USER_ONBOARDING_STATUS = 'GET_USER_ONBOARDING_STATUS',
  USER_ONBOARDING_STATUS_SUCCESS = 'USER_ONBOARDING_STATUS_SUCCESS',
  USER_ONBOARDING_STATUS_ERROR = 'USER_ONBOARDING_STATUS_ERROR',
  RESET_USER_ONBOARDING_STATUS = 'RESET_USER_ONBOARDING_STATUS'
};