export enum LOGGED_IN_USER_DETAILS_ACTIONS {
  GET_LOGGED_IN_USER_DETAILS_REQUEST = 'GET_LOGGED_IN_USER_DETAILS_REQUEST',
  GET_LOGGED_IN_USER_DETAILS_SUCCESS = 'GET_LOGGED_IN_USER_DETAILS_SUCCESS',
  GET_LOGGED_IN_USER_DETAILS_ERROR = 'GET_LOGGED_IN_USER_DETAILS_ERROR',
}
