export enum PRODUCT_CATEGORY_ACTIONS {
  PRODUCT_CATEGORY_REQUEST = 'PRODUCT_CATEGORY_REQUEST',
  PRODUCT_CATEGORY_SUCCESS = 'PRODUCT_CATEGORY_SUCCESS',
  PRODUCT_CATEGORY_ERROR = 'PRODUCT_CATEGORY_ERROR',
  PRODUCT_CATEGORY_RESET = 'PRODUCT_CATEGORY_RESET',
  PRODUCT_CATEGORY_REMOVE = 'PRODUCT_CATEGORY_REMOVE',

  GET_MORE_PRODUCT_CATEGORY_REQUEST = 'GET_MORE_PRODUCT_CATEGORY_REQUEST',
  GET_MORE_PRODUCT_CATEGORY_SUCCESS = 'GET_MORE_PRODUCT_CATEGORY_SUCCESS',
  GET_MORE_PRODUCT_CATEGORY_ERROR = 'GET_MORE_PRODUCT_CATEGORY_ERROR',

  PRODUCT_SUB_CATEGORY_REQUEST = 'PRODUCT_SUB_CATEGORY_REQUEST',
  PRODUCT_SUB_CATEGORY_SUCCESS = 'PRODUCT_SUB_CATEGORY_SUCCESS',
  PRODUCT_SUB_CATEGORY_ERROR = 'PRODUCT_SUB_CATEGORY_ERROR',
  PRODUCT_SUB_CATEGORY_RESET = 'PRODUCT_SUB_CATEGORY_RESET',
}
