export enum ACCOUNT_LIST_ACTIONS {
  GET_ACCOUNT_LIST_REQUEST = 'GET_ACCOUNT_LIST_REQUEST',
  GET_ACCOUNT_LIST_SUCCESS = 'GET_ACCOUNT_LIST_SUCCESS',
  GET_ACCOUNT_LIST_ERROR = 'GET_ACCOUNT_LIST_ERROR',

  GET_MORE_ACCOUNTS_REQUEST = 'GET_MORE_ACCOUNTS_REQUEST',
  GET_MORE_ACCOUNTS_SUCCESS = 'GET_MORE_ACCOUNTS_SUCCESS',
  GET_MORE_ACCOUNTS_ERROR = 'GET_MORE_ACCOUNTS_ERROR',
/* 
  SAVE_FILTER_REQUEST = 'SAVE_FILTER_REQUEST',
  SAVE_FILTER_SUCCESSS = 'SAVE_FILTER_SUCCESS',
  SAVE_FILTER_ERROR = 'SAVE_FILTER_ERROR', 
 */
  SET_CLIENT_IMAGE = 'SET_CLIENT_IMAGE',
  SET_ENABLED_APPS = 'SET_ENABLED_APPS'
}
