export enum CLIENT_DETAILS_ACTIONS {
  CLIENT_DETAILS_REQUEST = 'CLIENT_DETAILS_REQUEST',
  CLIENT_DETAILS_SUCCESS = 'CLIENT_DETAILS_SUCCESS',
  CLIENT_DETAILS_ERROR = 'CLIENT_DETAILS_ERROR',
  CLIENT_DETAILS_RESET = 'CLIENT_DETAILS_RESET',
}