export enum FILTER_CRITERIA_ACTIONS {
  FILTER_CRITERIA_REQUEST = 'FILTER_CRITERIA_REQUEST',
  FILTER_CRITERIA_SUCCESS = 'FILTER_CRITERIA_SUCCESS',
  FILTER_CRITERIA_ERROR = 'FILTER_CRITERIA_ERROR',
  FILTER_CRITERIA_RESET = 'FILTER_CRITERIA_RESET',

  SAVE_FILTER_REQUEST = 'SAVE_FILTER_REQUEST',
  SAVE_FILTER_SUCCESSS = 'SAVE_FILTER_SUCCESS',
  SAVE_FILTER_ERROR = 'SAVE_FILTER_ERROR', 

  SAVE_APPLIED_FILTER = 'SAVE_APPLIED_FILTER', 
  APPLY_FILTER_ID = 'APPLY_FILTER_ID',
  CLEAR_SAVED_APPLIED_FILTER = 'CLEAR_SAVED_APPLIED_FILTER',
  
}

export enum FILTER_CRITERIA_ACTIONS {
  FILTER_LIST_REQUEST = 'FILTER_LIST_REQUEST',
  FILTER_LIST_SUCCESS = 'FILTER_LIST_SUCCESS',
  FILTER_LIST_ERROR = 'FILTER_LIST_ERROR',
  FILTER_LIST_RESET = 'FILTER_LIST_RESET',
}

export enum FILTER_DELETE_ACTIONS {
  FILTER_DELETE_REQUEST = 'FILTER_DELETE_REQUEST',
  FILTER_DELETE_SUCCESS = 'FILTER_DELETE_SUCCESS',
  FILTER_DELETE_ERROR = 'FILTER_DELETE_ERROR',
  FILTER_DELETE_RESET = 'FILTER_DELETE_RESET',
}

export enum TAG_DATA_ACTIONS {
  TAGS_DATA_REQUEST = 'TAGS_DATA_REQUEST',
  TAGS_DATA_SUCCESS = 'TAGS_DATA_SUCCESS',
  TAGS_DATA_ERROR = 'TAGS_DATA_ERROR',
  TAGS_DATA_RESET = 'TAG_DATA_RESET',
}