export const ROUTES = {
  DEFAULT: '/',
  DASHBOARD: '/dashboard',
  LOGOUT: '/logout',
  CALLBACK: '/callback',
  UPLOAD: '/upload',
  ACCOUNT_DRILLDOWN: '/account-drilldown/:accountId',
  ACCOUNT_VIEW: '/account-view',
  TEAM_MANAGEMENT: '/team-management',
  ENGAGE_ACCOUNT_LIST: '/engage-canvas',
  ENGAGE_MICROSITES: '/engage-canvas/microsites',
  PULSE_HOME: '/pulse',
  CLIENTS_VIEW: '/clients-view',
  POLICY_ACCEPTANCE: '/policy-acceptance',
};
