export enum LEGAL_ENTITIES_ACTIONS {
  LEGAL_ENTITIES_REQUEST = 'LEGAL_ENTITIES_REQUEST',
  LEGAL_ENTITIES_SUCCESS = 'LEGAL_ENTITIES_SUCCESS',
  LEGAL_ENTITIES_ERROR = 'LEGAL_ENTITIES_ERROR',
  LEGAL_ENTITIES_RESET = 'LEGAL_ENTITIES_RESET',
}