export enum ACCOUNT_DETAILS_ACTIONS {
  ACCOUNT_DETAILS_REQUEST = 'ACCOUNT_DETAILS_REQUEST',
  ACCOUNT_DETAILS_SUCCESS = 'ACCOUNT_DETAILS_SUCCESS',
  ACCOUNT_DETAILS_ERROR = 'ACCOUNT_DETAILS_ERROR',
  ACCOUNT_DETAILS_RESET = 'ACCOUNT_DETAILS_RESET',
}

export enum ACCOUNT_USERS_ACTIONS {
  ACCOUNT_USERS_REQUEST = 'ACCOUNT_USERS_REQUEST',
  ACCOUNT_USERS_SUCCESS = 'ACCOUNT_USERS_SUCCESS',
  ACCOUNT_USERS_ERROR = 'ACCOUNT_USERS_ERROR',
  ACCOUNT_USERS_RESET = 'ACCOUNT_USERS_RESET',
  GET_MORE_ACCOUNT_USERS_REQUEST = 'GET_MORE_ACCOUNT_USERS_REQUEST',
  GET_MORE_ACCOUNT_USERS_SUCCESS = 'GET_MORE_ACCOUNT_USERS_SUCCESS',
  GET_MORE_ACCOUNT_USERS_ERROR = 'GET_MORE_ACCOUNT_USERS_ERROR',
}

export enum ACCOUNT_MATCHING_DATA_ACTIONS {
  ACCOUNT_MATCHING_DATA_REQUEST = 'ACCOUNT_MATCHING_DATA_REQUEST',
  ACCOUNT_MATCHING_DATA_SUCCESS = 'ACCOUNT_MATCHING_DATA_SUCCESS',
  ACCOUNT_MATCHING_DATA_ERROR = 'ACCOUNT_MATCHING_DATA_ERROR',
  ACCOUNT_MATCHING_DATA_RESET = 'ACCOUNT_MATCHING_DATA_RESET',
}

export enum ACC_MATCHING_SEARCH_DATA_ACTIONS {
  ACC_MATCHING_SEARCH_DATA_REQUEST = 'ACC_MATCHING_SEARCH_DATA_REQUEST',
  ACC_MATCHING_SEARCH_DATA_SUCCESS = 'ACC_MATCHING_SEARCH_DATA_SUCCESS',
  ACC_MATCHING_SEARCH_DATA_ERROR = 'ACC_MATCHING_SEARCH_DATA_ERROR',
  ACC_MATCHING_SEARCH_DATA_RESET = 'ACC_MATCHING_SEARCH_DATA_RESET',
}

export enum UPDATE_ACC_MATCHING_DATA_ACTIONS {
  UPDATE_ACC_MATCHING_DATA_REQUEST = 'UPDATE_ACC_MATCHING_DATA_REQUEST',
  UPDATE_ACC_MATCHING_DATA_SUCCESS = 'UPDATE_ACC_MATCHING_DATA_SUCCESS',
  UPDATE_ACC_MATCHING_DATA_ERROR = 'UPDATE_ACC_MATCHING_DATA_ERROR',
  UPDATE_ACC_MATCHING_DATA_RESET = 'UPDATE_ACC_MATCHING_DATA_RESET',
}