export enum POLICY_AGREEMENT_ACTIONS {
  ACCEPT_POLICY_CONSENT_REQUEST = "ACCEPT_POLICY_CONSENT_REQUEST",
  ACCEPT_POLICY_CONSENT_SUCCESS = "ACCEPT_POLICY_CONSENT_SUCCESS",
  ACCEPT_POLICY_CONSENT_ERROR = "ACCEPT_POLICY_CONSENT_ERROR",
  FETCH_POLICY_CONSENT_REQUEST = "FETCH_POLICY_CONSENT_REQUEST",
  FETCH_POLICY_CONSENT_SUCCESS = "FETCH_POLICY_CONSENT_SUCCESS",
  FETCH_POLICY_CONSENT_ERROR = "FETCH_POLICY_CONSENT_ERROR"
};