export enum AUTH_ACTIONS {
  INIT_SESSION = 'INIT_SESSION',
  CLEAR_SESSION = 'CLEAR_SESSION', 
  SET_SESSION = 'SET_SESSION',
  GET_USER_LIST = 'GET_USER_LIST',
  SET_USERS_DETAILS = 'SET_USERS_DETAILS',
};