export enum SITE_SELECTION_ACTIONS {
  SITE_SELECTION_REQUEST = 'SITE_SELECTION_REQUEST',
  SITE_SELECTION_SUCCESS = 'SITE_SELECTION_SUCCESS',
  SITE_SELECTION_ERROR = 'SITE_SELECTION_ERROR',
  SITE_SELECTION_RESET = 'SITE_SELECTION_RESET',
  CHANGE_SITE_SELECTION = 'CHANGE_SITE_SELECTION',
  GET_ACCOUNT_SITE = 'GET_ACCOUNT_SITE'
}